pipeline {
    agent any

    environment {
        IMAGE_NAME = "calculator-app" // Replace with your Docker Hub username and image name
    }

    stages {
        stage("Clone Repo") {
            steps {
                git branch: 'main', url: 'https://github.com/Git-Prajwal-GH/calculator-py-based.git' // Clone the repository
            }
        }

        stage("Build Docker Image") {
            steps {
                sh "docker build -t ${IMAGE_NAME}:latest ." // Specify Dockerfile location
            }
        }

        stage("Push to Docker Hub") {
            steps {
                withCredentials([usernamePassword('credentialsId': "dockerhub_cred",
                    passwordVariable: "dockerHubPass",
                    usernameVariable: "dockerHubUser")]){
                sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass} " // Login to Docker Hub
                sh "docker image tag ${IMAGE_NAME}:latest ${env.dockerHubUser}/${IMAGE_NAME}:latest" // Tag the image
                sh "docker push ${env.dockerHubUser}/${IMAGE_NAME}:latest" // Push the image
            }
          }
        }

        stage("Deploy Container") {
            steps {
                sh "docker run -d -p 5000:5000 --name calc-app ${IMAGE_NAME}:latest"
            }
        }
    } // End of stages
} // End of pipeline
