pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')  // Jenkins credential ID
        IMAGE_NAME = "prajwalgh/calculator-app" // Replace with your Docker Hub username and image name
    }

    stages {
        stage("Clone Repo") {
            steps {
                git branch: 'main', url: 'https://github.com/Git-Prajwal-GH/calculator-py-based.git'
            }
        }

        stage("Build Docker Image") {
            steps {
                sh "docker build -t ${IMAGE_NAME}:latest ."
            }
        }

        stage("Push to Docker Hub") {
            steps {
                withCredentials([usernamePassword('credentialsId':"dockerhub_cred",passwordVariable:"dockerHubPass",usernameVariable:"dockerHubUser")]){
                sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass} " // Login to Docker Hub
                sh "docker image tag ${IMAGE_NAME}:latest ${env.dockerHubUser}/calculator-app:latest" // Tag the image
                sh "docker push ${env.dockerHubUser}/calculator-app:latest" // Push the image
            }
        }

        stage("Deploy Container") {
            steps {
                sh "docker run -d -p 5000:5000 --name calc-app ${IMAGE_NAME}:latest"
            }
        }
    }
 }
}